"""empty message

Revision ID: 12e96b901203
Revises: 
Create Date: 2019-09-14 10:34:12.496056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e96b901203'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('brandId', sa.String(length=80), nullable=False),
    sa.Column('brandName', sa.String(length=50), nullable=False),
    sa.Column('createDate', sa.BigInteger(), nullable=True),
    sa.Column('updateDate', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('brandId', name=op.f('pk_brands'))
    )
    op.create_table('catagories',
    sa.Column('catId', sa.String(length=80), nullable=False),
    sa.Column('catName', sa.String(length=50), nullable=False),
    sa.Column('createDate', sa.BigInteger(), nullable=True),
    sa.Column('updateDate', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('catId', name=op.f('pk_catagories'))
    )
    op.create_table('users',
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('createDate', sa.BigInteger(), nullable=True),
    sa.Column('updateDate', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('userId', name=op.f('pk_users'))
    )
    op.create_table('orders',
    sa.Column('orderId', sa.String(length=80), nullable=False),
    sa.Column('createDate', sa.BigInteger(), nullable=True),
    sa.Column('updateDate', sa.BigInteger(), nullable=True),
    sa.Column('userId', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], name=op.f('fk_orders_userId_users')),
    sa.PrimaryKeyConstraint('orderId', name=op.f('pk_orders'))
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('facebook', sa.String(length=80), nullable=True),
    sa.Column('instragram', sa.String(length=80), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('createDate', sa.BigInteger(), nullable=True),
    sa.Column('updateDate', sa.BigInteger(), nullable=True),
    sa.Column('userId', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], name=op.f('fk_profile_userId_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile'))
    )
    op.create_table('store',
    sa.Column('storeId', sa.String(length=80), nullable=False),
    sa.Column('storeName', sa.String(length=40), nullable=False),
    sa.Column('storeLocation', sa.Text(), nullable=True),
    sa.Column('storeCoverImage', sa.Text(), nullable=True),
    sa.Column('storePicture', sa.Text(), nullable=True),
    sa.Column('createDate', sa.BigInteger(), nullable=True),
    sa.Column('updateDate', sa.BigInteger(), nullable=True),
    sa.Column('userId', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], name=op.f('fk_store_userId_users')),
    sa.PrimaryKeyConstraint('storeId', name=op.f('pk_store'))
    )
    op.create_table('orderhistories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('flaskSaleStatus', sa.Boolean(), nullable=True),
    sa.Column('createDate', sa.BigInteger(), nullable=True),
    sa.Column('updateDate', sa.BigInteger(), nullable=True),
    sa.Column('orderId', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['orderId'], ['orders.orderId'], name=op.f('fk_orderhistories_orderId_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orderhistories'))
    )
    op.create_table('products',
    sa.Column('proId', sa.String(length=80), nullable=False),
    sa.Column('proName', sa.String(length=50), nullable=False),
    sa.Column('proPrice', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('proImg', sa.Text(), nullable=True),
    sa.Column('proQuantity', sa.Integer(), nullable=True),
    sa.Column('feature', sa.Text(), nullable=True),
    sa.Column('flashSaleStatus', sa.Boolean(), nullable=True),
    sa.Column('authorId', sa.String(length=80), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('createDate', sa.BigInteger(), nullable=True),
    sa.Column('updateDate', sa.BigInteger(), nullable=True),
    sa.Column('catId', sa.String(length=80), nullable=False),
    sa.Column('userId', sa.String(length=80), nullable=False),
    sa.Column('storeId', sa.String(length=80), nullable=False),
    sa.Column('brandId', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['brandId'], ['brands.brandId'], name=op.f('fk_products_brandId_brands')),
    sa.ForeignKeyConstraint(['catId'], ['catagories.catId'], name=op.f('fk_products_catId_catagories')),
    sa.ForeignKeyConstraint(['storeId'], ['store.storeId'], name=op.f('fk_products_storeId_store')),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], name=op.f('fk_products_userId_users')),
    sa.PrimaryKeyConstraint('proId', name=op.f('pk_products'))
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commentId', sa.String(length=70), nullable=False),
    sa.Column('commentRating', sa.Integer(), nullable=True),
    sa.Column('commentMsg', sa.Text(), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=True),
    sa.Column('proId', sa.String(length=50), nullable=True),
    sa.Column('createDate', sa.BigInteger(), nullable=True),
    sa.Column('updateDate', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['proId'], ['products.proId'], name=op.f('fk_comments_proId_products')),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], name=op.f('fk_comments_userId_users')),
    sa.PrimaryKeyConstraint('id', 'commentId', name=op.f('pk_comments'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('products')
    op.drop_table('orderhistories')
    op.drop_table('store')
    op.drop_table('profile')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('catagories')
    op.drop_table('brands')
    # ### end Alembic commands ###
