"""empty message

Revision ID: 1e7fe2bf6d81
Revises: a56ea3efab8c
Create Date: 2019-09-19 08:31:54.662067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e7fe2bf6d81'
down_revision = 'a56ea3efab8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderhistories', schema=None) as batch_op:
        batch_op.alter_column('flaskSaleStatus',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inOrederStatus', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('inOrederStatus')

    with op.batch_alter_table('orderhistories', schema=None) as batch_op:
        batch_op.alter_column('flaskSaleStatus',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###
