"""empty message

Revision ID: 5713ce237a8b
Revises: 12e96b901203
Create Date: 2019-09-14 15:26:47.584080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5713ce237a8b'
down_revision = '12e96b901203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('storeId',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=True)
        batch_op.alter_column('userId',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=True)
        batch_op.drop_column('authorId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorId', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80), nullable=False))
        batch_op.alter_column('userId',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=False)
        batch_op.alter_column('storeId',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=False)

    # ### end Alembic commands ###
