"""empty message

Revision ID: a56ea3efab8c
Revises: 5713ce237a8b
Create Date: 2019-09-18 11:31:13.750149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56ea3efab8c'
down_revision = '5713ce237a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderhistories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proId', sa.String(length=80), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_orderhistories_proId_products'), 'products', ['proId'], ['proId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderhistories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orderhistories_proId_products'), type_='foreignkey')
        batch_op.drop_column('proId')

    # ### end Alembic commands ###
